// <auto-generated />
using MVC1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220830120227_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVC1.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Indonesia",
                            First_name = "Gary",
                            Last_name = "Ortiz",
                            Tel = "07395539"
                        },
                        new
                        {
                            Id = 2,
                            Country = "China",
                            First_name = "Albert",
                            Last_name = "Williamson",
                            Tel = "0739439"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Peru",
                            First_name = "Mildred",
                            Last_name = "Fuller",
                            Tel = "07378539"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Belarus",
                            First_name = "Russell",
                            Last_name = "Robinson",
                            Tel = "07323539"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Philippines",
                            First_name = "Laura",
                            Last_name = "Harper",
                            Tel = "07395659"
                        },
                        new
                        {
                            Id = 6,
                            Country = "China",
                            First_name = "Larry",
                            Last_name = "Sanders",
                            Tel = "07395539"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Philippines",
                            First_name = "Michael",
                            Last_name = "Rice",
                            Tel = "073955546"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Indonesia",
                            First_name = "Sara",
                            Last_name = "Harris",
                            Tel = "07395556"
                        },
                        new
                        {
                            Id = 9,
                            Country = "China",
                            First_name = "Phyllis",
                            Last_name = "Webb",
                            Tel = "073955576"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Finland",
                            First_name = "Roger",
                            Last_name = "Alvarez",
                            Tel = "073955321"
                        },
                        new
                        {
                            Id = 11,
                            Country = "Sweden",
                            First_name = "Maria",
                            Last_name = "Carpenter",
                            Tel = "0739551234"
                        },
                        new
                        {
                            Id = 12,
                            Country = "Russia",
                            First_name = "Lori",
                            Last_name = "Edwards",
                            Tel = "073955353"
                        },
                        new
                        {
                            Id = 13,
                            Country = "Russia",
                            First_name = "Phillip",
                            Last_name = "Mitchell",
                            Tel = "0739553321"
                        },
                        new
                        {
                            Id = 14,
                            Country = "Indonesia",
                            First_name = "Craig",
                            Last_name = "Lopez",
                            Tel = "0739551249"
                        },
                        new
                        {
                            Id = 15,
                            Country = "Mauritius",
                            First_name = "Marie",
                            Last_name = "George",
                            Tel = "073955234"
                        },
                        new
                        {
                            Id = 16,
                            Country = "Norway",
                            First_name = "Jean",
                            Last_name = "Duncan",
                            Tel = "07395541"
                        },
                        new
                        {
                            Id = 17,
                            Country = "Sweden",
                            First_name = "Kimberly",
                            Last_name = "Butler",
                            Tel = "073955412"
                        },
                        new
                        {
                            Id = 18,
                            Country = "Indonesia",
                            First_name = "Heather",
                            Last_name = "Ramirez",
                            Tel = "073951234"
                        },
                        new
                        {
                            Id = 19,
                            Country = "Canada",
                            First_name = "Jason",
                            Last_name = "Sanders",
                            Tel = "073955214"
                        },
                        new
                        {
                            Id = 20,
                            Country = "Philippines",
                            First_name = "Juan",
                            Last_name = "Evans",
                            Tel = "073955214"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
