// <auto-generated />
using System;
using MVC1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC1.Migrations
{
    [DbContext(typeof(MVC1Context))]
    partial class MVC1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "79622611-cf1b-4315-ada8-bca5b06f56a3",
                            AccessFailedCount = 0,
                            BirthDay = new DateTime(2022, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ConcurrencyStamp = "bcfeec4b-b27c-4036-baf6-8f86e777fa96",
                            Email = "bhroz@bhroz.com",
                            EmailConfirmed = false,
                            FirstName = "Damsaz",
                            LastName = "behroz",
                            LockoutEnabled = false,
                            NormalizedEmail = "bhroz@bhroz.com",
                            NormalizedUserName = "bhroz@bhroz.com",
                            PasswordHash = "AQAAAAEAACcQAAAAED5/67skP8C1dj7tyffWwnrzbFd/3A8x29dnmLessCs3lziTJcyUFR+5JSy0ZqcqYw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5061857a-6dcc-4b80-be53-644373f834f2",
                            TwoFactorEnabled = false,
                            UserName = "bhroz@bhroz.com"
                        });
                });

            modelBuilder.Entity("LanguagePerson", b =>
                {
                    b.Property<int>("LanguagesIdLanguage")
                        .HasColumnType("int");

                    b.Property<int>("peopleId")
                        .HasColumnType("int");

                    b.HasKey("LanguagesIdLanguage", "peopleId");

                    b.HasIndex("peopleId");

                    b.ToTable("LanguagePerson");

                    b.HasData(
                        new
                        {
                            LanguagesIdLanguage = 1,
                            peopleId = 1
                        },
                        new
                        {
                            LanguagesIdLanguage = 2,
                            peopleId = 1
                        },
                        new
                        {
                            LanguagesIdLanguage = 2,
                            peopleId = 2
                        },
                        new
                        {
                            LanguagesIdLanguage = 1,
                            peopleId = 3
                        },
                        new
                        {
                            LanguagesIdLanguage = 2,
                            peopleId = 4
                        },
                        new
                        {
                            LanguagesIdLanguage = 2,
                            peopleId = 5
                        },
                        new
                        {
                            LanguagesIdLanguage = 1,
                            peopleId = 6
                        },
                        new
                        {
                            LanguagesIdLanguage = 2,
                            peopleId = 7
                        },
                        new
                        {
                            LanguagesIdLanguage = 2,
                            peopleId = 8
                        },
                        new
                        {
                            LanguagesIdLanguage = 1,
                            peopleId = 9
                        },
                        new
                        {
                            LanguagesIdLanguage = 2,
                            peopleId = 10
                        },
                        new
                        {
                            LanguagesIdLanguage = 2,
                            peopleId = 11
                        },
                        new
                        {
                            LanguagesIdLanguage = 1,
                            peopleId = 12
                        },
                        new
                        {
                            LanguagesIdLanguage = 1,
                            peopleId = 13
                        },
                        new
                        {
                            LanguagesIdLanguage = 1,
                            peopleId = 14
                        },
                        new
                        {
                            LanguagesIdLanguage = 2,
                            peopleId = 15
                        },
                        new
                        {
                            LanguagesIdLanguage = 2,
                            peopleId = 12
                        },
                        new
                        {
                            LanguagesIdLanguage = 3,
                            peopleId = 13
                        },
                        new
                        {
                            LanguagesIdLanguage = 4,
                            peopleId = 14
                        },
                        new
                        {
                            LanguagesIdLanguage = 3,
                            peopleId = 15
                        },
                        new
                        {
                            LanguagesIdLanguage = 3,
                            peopleId = 16
                        },
                        new
                        {
                            LanguagesIdLanguage = 4,
                            peopleId = 17
                        },
                        new
                        {
                            LanguagesIdLanguage = 4,
                            peopleId = 12
                        },
                        new
                        {
                            LanguagesIdLanguage = 4,
                            peopleId = 13
                        },
                        new
                        {
                            LanguagesIdLanguage = 2,
                            peopleId = 14
                        },
                        new
                        {
                            LanguagesIdLanguage = 1,
                            peopleId = 15
                        },
                        new
                        {
                            LanguagesIdLanguage = 1,
                            peopleId = 18
                        },
                        new
                        {
                            LanguagesIdLanguage = 1,
                            peopleId = 19
                        },
                        new
                        {
                            LanguagesIdLanguage = 1,
                            peopleId = 20
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "51a8da7c-f25e-49b4-ada9-67f8f4819a6e",
                            ConcurrencyStamp = "a8e407a3-b5fb-4780-a17d-bbf09fcbbaf2",
                            Name = "User",
                            NormalizedName = "User"
                        },
                        new
                        {
                            Id = "5e487a9c-15e3-4d88-a52e-92f550741892",
                            ConcurrencyStamp = "fdb6dae6-7546-4226-8ce8-54c43b1322ed",
                            Name = "Administrator",
                            NormalizedName = "Administrator"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "79622611-cf1b-4315-ada8-bca5b06f56a3",
                            RoleId = "5e487a9c-15e3-4d88-a52e-92f550741892"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MVC1.Models.City", b =>
                {
                    b.Property<int>("IdCity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCity"), 1L, 1);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdCity");

                    b.HasIndex("CountryId");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            IdCity = 1,
                            CityName = "Jakarta",
                            CountryId = "ID"
                        },
                        new
                        {
                            IdCity = 2,
                            CityName = "Kampinos",
                            CountryId = "PL"
                        },
                        new
                        {
                            IdCity = 3,
                            CityName = "Beacon",
                            CountryId = "US"
                        },
                        new
                        {
                            IdCity = 4,
                            CityName = "Caldelas",
                            CountryId = "PT"
                        },
                        new
                        {
                            IdCity = 5,
                            CityName = "Tehran",
                            CountryId = "IR"
                        },
                        new
                        {
                            IdCity = 6,
                            CityName = "Mantorp",
                            CountryId = "SE"
                        },
                        new
                        {
                            IdCity = 7,
                            CityName = "Saint-Maximin",
                            CountryId = "FR"
                        },
                        new
                        {
                            IdCity = 8,
                            CityName = "Nickerson",
                            CountryId = "US"
                        },
                        new
                        {
                            IdCity = 9,
                            CityName = "Dippach",
                            CountryId = "DE"
                        },
                        new
                        {
                            IdCity = 10,
                            CityName = "Floresta",
                            CountryId = "IT"
                        },
                        new
                        {
                            IdCity = 11,
                            CityName = "Alpine",
                            CountryId = "US"
                        },
                        new
                        {
                            IdCity = 12,
                            CityName = "Crissey",
                            CountryId = "FR"
                        },
                        new
                        {
                            IdCity = 13,
                            CityName = "Dundee",
                            CountryId = "GB"
                        },
                        new
                        {
                            IdCity = 14,
                            CityName = "Aiguaviva",
                            CountryId = "ES"
                        },
                        new
                        {
                            IdCity = 15,
                            CityName = "Tecate",
                            CountryId = "MX"
                        },
                        new
                        {
                            IdCity = 16,
                            CityName = "Amapa",
                            CountryId = "MX"
                        },
                        new
                        {
                            IdCity = 17,
                            CityName = "Arauca",
                            CountryId = "CO"
                        },
                        new
                        {
                            IdCity = 18,
                            CityName = "Derventa",
                            CountryId = "BA"
                        },
                        new
                        {
                            IdCity = 19,
                            CityName = "Schignano",
                            CountryId = "IT"
                        },
                        new
                        {
                            IdCity = 20,
                            CityName = "Raceview",
                            CountryId = "AU"
                        });
                });

            modelBuilder.Entity("MVC1.Models.Country", b =>
                {
                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            CountryId = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            CountryId = "AX",
                            Name = "land Islands"
                        },
                        new
                        {
                            CountryId = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            CountryId = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            CountryId = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            CountryId = "AD",
                            Name = "AndorrA"
                        },
                        new
                        {
                            CountryId = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            CountryId = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            CountryId = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            CountryId = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            CountryId = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            CountryId = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            CountryId = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            CountryId = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            CountryId = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            CountryId = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            CountryId = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            CountryId = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            CountryId = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            CountryId = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            CountryId = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            CountryId = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            CountryId = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            CountryId = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            CountryId = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            CountryId = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            CountryId = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            CountryId = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            CountryId = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            CountryId = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            CountryId = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            CountryId = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            CountryId = "BN",
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            CountryId = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            CountryId = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            CountryId = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            CountryId = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            CountryId = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            CountryId = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            CountryId = "CV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            CountryId = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            CountryId = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            CountryId = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            CountryId = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            CountryId = "CN",
                            Name = "China"
                        },
                        new
                        {
                            CountryId = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            CountryId = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            CountryId = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            CountryId = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            CountryId = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            CountryId = "CD",
                            Name = "Congo, The Democratic Republic of the"
                        },
                        new
                        {
                            CountryId = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            CountryId = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            CountryId = "CI",
                            Name = "Cote D\"Ivoire"
                        },
                        new
                        {
                            CountryId = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            CountryId = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            CountryId = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            CountryId = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            CountryId = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            CountryId = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            CountryId = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            CountryId = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            CountryId = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            CountryId = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            CountryId = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            CountryId = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            CountryId = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            CountryId = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            CountryId = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            CountryId = "FK",
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            CountryId = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            CountryId = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            CountryId = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            CountryId = "FR",
                            Name = "France"
                        },
                        new
                        {
                            CountryId = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            CountryId = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            CountryId = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            CountryId = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            CountryId = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            CountryId = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            CountryId = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            CountryId = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            CountryId = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            CountryId = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            CountryId = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            CountryId = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            CountryId = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            CountryId = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            CountryId = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            CountryId = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            CountryId = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            CountryId = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            CountryId = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            CountryId = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            CountryId = "HM",
                            Name = "Heard Island and Mcdonald Islands"
                        },
                        new
                        {
                            CountryId = "VA",
                            Name = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            CountryId = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            CountryId = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            CountryId = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            CountryId = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            CountryId = "IN",
                            Name = "India"
                        },
                        new
                        {
                            CountryId = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            CountryId = "IR",
                            Name = "Iran, Islamic Republic Of"
                        },
                        new
                        {
                            CountryId = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            CountryId = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            CountryId = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            CountryId = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            CountryId = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            CountryId = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            CountryId = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            CountryId = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            CountryId = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            CountryId = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            CountryId = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            CountryId = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            CountryId = "KP",
                            Name = "Korea, Democratic People\"S Republic of"
                        },
                        new
                        {
                            CountryId = "KR",
                            Name = "Korea, Republic of"
                        },
                        new
                        {
                            CountryId = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            CountryId = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            CountryId = "LA",
                            Name = "Lao People\"S Democratic Republic"
                        },
                        new
                        {
                            CountryId = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            CountryId = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            CountryId = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            CountryId = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            CountryId = "LY",
                            Name = "Libyan Arab Jamahiriya"
                        },
                        new
                        {
                            CountryId = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            CountryId = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            CountryId = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            CountryId = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            CountryId = "MK",
                            Name = "Macedonia, The Former Yugoslav Republic of"
                        },
                        new
                        {
                            CountryId = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            CountryId = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            CountryId = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            CountryId = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            CountryId = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            CountryId = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            CountryId = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            CountryId = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            CountryId = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            CountryId = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            CountryId = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            CountryId = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            CountryId = "FM",
                            Name = "Micronesia, Federated States of"
                        },
                        new
                        {
                            CountryId = "MD",
                            Name = "Moldova, Republic of"
                        },
                        new
                        {
                            CountryId = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            CountryId = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            CountryId = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            CountryId = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            CountryId = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            CountryId = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            CountryId = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            CountryId = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            CountryId = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            CountryId = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            CountryId = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            CountryId = "AN",
                            Name = "Netherlands Antilles"
                        },
                        new
                        {
                            CountryId = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            CountryId = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            CountryId = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            CountryId = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            CountryId = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            CountryId = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            CountryId = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            CountryId = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            CountryId = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            CountryId = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            CountryId = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            CountryId = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            CountryId = "PS",
                            Name = "Palestinian Territory, Occupied"
                        },
                        new
                        {
                            CountryId = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            CountryId = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            CountryId = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            CountryId = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            CountryId = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            CountryId = "PN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            CountryId = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            CountryId = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            CountryId = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            CountryId = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            CountryId = "RE",
                            Name = "Reunion"
                        },
                        new
                        {
                            CountryId = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            CountryId = "RU",
                            Name = "Russian Federation"
                        },
                        new
                        {
                            CountryId = "RW",
                            Name = "RWANDA"
                        },
                        new
                        {
                            CountryId = "SH",
                            Name = "Saint Helena"
                        },
                        new
                        {
                            CountryId = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            CountryId = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            CountryId = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            CountryId = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            CountryId = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            CountryId = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            CountryId = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            CountryId = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            CountryId = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            CountryId = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            CountryId = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            CountryId = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            CountryId = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            CountryId = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            CountryId = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            CountryId = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            CountryId = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            CountryId = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            CountryId = "GS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            CountryId = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            CountryId = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            CountryId = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            CountryId = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            CountryId = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            CountryId = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            CountryId = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            CountryId = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            CountryId = "SY",
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            CountryId = "TW",
                            Name = "Taiwan, Province of China"
                        },
                        new
                        {
                            CountryId = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            CountryId = "TZ",
                            Name = "Tanzania, United Republic of"
                        },
                        new
                        {
                            CountryId = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            CountryId = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            CountryId = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            CountryId = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            CountryId = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            CountryId = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            CountryId = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            CountryId = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            CountryId = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            CountryId = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            CountryId = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            CountryId = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            CountryId = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            CountryId = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            CountryId = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            CountryId = "US",
                            Name = "United States"
                        },
                        new
                        {
                            CountryId = "UM",
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            CountryId = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            CountryId = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            CountryId = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            CountryId = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            CountryId = "VN",
                            Name = "Viet Nam"
                        },
                        new
                        {
                            CountryId = "VG",
                            Name = "Virgin Islands, British"
                        },
                        new
                        {
                            CountryId = "VI",
                            Name = "Virgin Islands, U.S."
                        },
                        new
                        {
                            CountryId = "WF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            CountryId = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            CountryId = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            CountryId = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            CountryId = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("MVC1.Models.Language", b =>
                {
                    b.Property<int>("IdLanguage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLanguage"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLanguage");

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            IdLanguage = 1,
                            Name = "En"
                        },
                        new
                        {
                            IdLanguage = 2,
                            Name = "Sv"
                        },
                        new
                        {
                            IdLanguage = 3,
                            Name = "Fr"
                        },
                        new
                        {
                            IdLanguage = 4,
                            Name = "Fa"
                        },
                        new
                        {
                            IdLanguage = 5,
                            Name = "Ar"
                        });
                });

            modelBuilder.Entity("MVC1.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCity")
                        .HasColumnType("int");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCity");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            First_name = "Gary",
                            IdCity = 1,
                            Last_name = "Ortiz",
                            Tel = "07395539"
                        },
                        new
                        {
                            Id = 2,
                            First_name = "Albert",
                            IdCity = 2,
                            Last_name = "Williamson",
                            Tel = "0739439"
                        },
                        new
                        {
                            Id = 3,
                            First_name = "Mildred",
                            IdCity = 3,
                            Last_name = "Fuller",
                            Tel = "07378539"
                        },
                        new
                        {
                            Id = 4,
                            First_name = "Russell",
                            IdCity = 4,
                            Last_name = "Robinson",
                            Tel = "07323539"
                        },
                        new
                        {
                            Id = 5,
                            First_name = "Laura",
                            IdCity = 5,
                            Last_name = "Harper",
                            Tel = "07395659"
                        },
                        new
                        {
                            Id = 6,
                            First_name = "Larry",
                            IdCity = 6,
                            Last_name = "Sanders",
                            Tel = "07395539"
                        },
                        new
                        {
                            Id = 7,
                            First_name = "Michael",
                            IdCity = 7,
                            Last_name = "Rice",
                            Tel = "073955546"
                        },
                        new
                        {
                            Id = 8,
                            First_name = "Sara",
                            IdCity = 8,
                            Last_name = "Harris",
                            Tel = "07395556"
                        },
                        new
                        {
                            Id = 9,
                            First_name = "Phyllis",
                            IdCity = 9,
                            Last_name = "Webb",
                            Tel = "073955576"
                        },
                        new
                        {
                            Id = 10,
                            First_name = "Roger",
                            IdCity = 10,
                            Last_name = "Alvarez",
                            Tel = "073955321"
                        },
                        new
                        {
                            Id = 11,
                            First_name = "Maria",
                            IdCity = 11,
                            Last_name = "Carpenter",
                            Tel = "0739551234"
                        },
                        new
                        {
                            Id = 12,
                            First_name = "Lori",
                            IdCity = 12,
                            Last_name = "Edwards",
                            Tel = "073955353"
                        },
                        new
                        {
                            Id = 13,
                            First_name = "Phillip",
                            IdCity = 13,
                            Last_name = "Mitchell",
                            Tel = "0739553321"
                        },
                        new
                        {
                            Id = 14,
                            First_name = "Craig",
                            IdCity = 14,
                            Last_name = "Lopez",
                            Tel = "0739551249"
                        },
                        new
                        {
                            Id = 15,
                            First_name = "Marie",
                            IdCity = 15,
                            Last_name = "George",
                            Tel = "073955234"
                        },
                        new
                        {
                            Id = 16,
                            First_name = "Jean",
                            IdCity = 16,
                            Last_name = "Duncan",
                            Tel = "07395541"
                        },
                        new
                        {
                            Id = 17,
                            First_name = "Kimberly",
                            IdCity = 17,
                            Last_name = "Butler",
                            Tel = "073955412"
                        },
                        new
                        {
                            Id = 18,
                            First_name = "Heather",
                            IdCity = 18,
                            Last_name = "Ramirez",
                            Tel = "073951234"
                        },
                        new
                        {
                            Id = 19,
                            First_name = "Jason",
                            IdCity = 19,
                            Last_name = "Sanders",
                            Tel = "073955214"
                        },
                        new
                        {
                            Id = 20,
                            First_name = "Juan",
                            IdCity = 20,
                            Last_name = "Evans",
                            Tel = "073955214"
                        });
                });

            modelBuilder.Entity("LanguagePerson", b =>
                {
                    b.HasOne("MVC1.Models.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesIdLanguage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC1.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("peopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MVC1.Models.City", b =>
                {
                    b.HasOne("MVC1.Models.Country", "Country")
                        .WithMany("City")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MVC1.Models.Person", b =>
                {
                    b.HasOne("MVC1.Models.City", "city")
                        .WithMany("people")
                        .HasForeignKey("IdCity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");
                });

            modelBuilder.Entity("MVC1.Models.City", b =>
                {
                    b.Navigation("people");
                });

            modelBuilder.Entity("MVC1.Models.Country", b =>
                {
                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
